let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Belizean Boy",
    price: 459999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Red Liner",
    price: 375999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Forest Owl",
    price: 349999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Trails",
    price: 289999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mount Fishy",
    price: 223999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "On Arrow",
    price: 222999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Sky Plane",
    price: 189999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Crusie Fly",
    price:175999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Mortage Wood",
    price:179999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Gaint Bull",
    price: 169999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Sand Crunch",
    price: 139999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Boot Den",
    price: 129999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "./images/img-12.jpg",
  },
];
